### PR TITLE
stdlib: Add quasiquote.kl, list.kl

### PR DESCRIPTION
**Pull request by langston-barrett**
Progress on #54

### CODE REVIEW

**Comment by langston-barrett** [comment]
I'm not entirely sure what's up with the remaining failure:
```
    bool:                                              Expected 3 entries between parentheses, but got
  #[bool.kl:26.24-27.68]<(#%app binary-and (true) (and (true) (true)))>
FAIL (0.04s)
      user error
```

**Comment by david-christiansen** [comment]
Probably it's using n-ary function application in a file where the language doesn't have that.

**Comment by david-christiansen** [comment]
Looking at this a little more, it looks like it's picking the wrong `#%app` in the expansion of the `and` macro. 

When I switch line 26-27 to:
```
                (pure (list-syntax ('binary-and x
                                               (cons-list-syntax 'and xs stx)) stx))))))))

```
it works. This makes me think that it's a bug in the quasiquote macro, where it's picking the wrong lexical context, but I don't know for sure.

**Comment by david-christiansen** [comment]
Yep, that was it. This fixes it:
```
modified   stdlib/quasiquote.kl
@@ -49,14 +49,14 @@
                                                       (list-syntax ('quasiquote s)
                                                                    s))
                                                     e)
-                                        (list-syntax ('quote (replace-loc e 'foo)) 'foo))
+                                        (list-syntax ('quote e) e))
                                       e)]]]]]
               [_ [pure
                   (list-syntax ('list-syntax
                                   (map-syntax (lambda (s)
                                                 (list-syntax ('quasiquote s) s))
                                               e)
-                                  (list-syntax ('quote (replace-loc e 'foo)) 'foo))
+                                  (list-syntax ('quote e) e))
                                 e)]])])]
         [_ (syntax-error [list-syntax [[quote "bad syntax"] stx] stx] stx)])]])]
 
```

There's no way to send a PR to a PR as far as I can see, unfortunately.

**Comment by langston-barrett** [comment]
@david-christiansen Thanks for taking a detailed look! I'll add that to this branch soonish.

**Comment by david-christiansen** [comment]
It looks to me like a golden file needs updating.

**Comment by david-christiansen** [comment]
Ah, the golden file is right for your branch, but not for the result of merging in `master`, where `Signal` is no more. What about merging master and then running CI again?

**Pull request merged**
