### PR TITLE
Fix type-case bug

### LINKED ISSUE #145: "Type pattern info not added" when matching on builtins of kind Type
(define-macro (type-name)
      (>>= (which-problem)
           (lambda (prob)
             (case prob
               [(expression t)
                (type-case t
                  [(-> a b)
                   (pure '"arrow")]
                  [String
                   (pure '"string")])]))))
    
    --   Internal error during expansion! This is a bug in the implementation.
    --   Type pattern info not added
    (example (the String (type-name)))

The same happens with the types `Syntax`, `Integer`, and `Type`, but not with `(-> a b)`, `(Macro a)`, `(IO a)`, `Unit`, `Bool`, `(Maybe a)`, nor `(List a)`, so the bug seems to be about matching on builtin types of kind `Type`.

### PR DESCRIPTION
**Pull request by gelisam**
Fixes #145

### CODE REVIEW

**Comment by david-christiansen** [comment]
Shouldn't the comment in which-problem.kl be deleted now that you've fixed it?

**Comment by gelisam** [comment]
> Shouldn't the comment in which-problem.kl be deleted now that you've fixed it?

fixed, thanks!

**Comment by gelisam** [comment]
I'm thinking of improving this further by merging `_expanderCompletedTypePatterns` and `_expanderTypePatternBinders` into a single Map, to make illegal states unrepresentable.

**Comment by gelisam** [comment]
Nah, there are too many other similar pairs of fields in ExpanderState. I don't want to make a big refactoring which would make _everything_ unrepresentable, and I don't want to make a small refactoring which would let readers wonder why type patterns are represented one way while regular patterns are represented in a different way. I'll leave things as-is, improving `linkTypePattern` was good enough.

**Comment by david-christiansen** [comment]
It's nice seeing more work on Klister!

**Pull request merged**
